
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author feda1
 */
public class SİPARİSUYGULAMA extends javax.swing.JFrame {
Map<String,Integer> siparisler=new LinkedHashMap<String, Integer>();
    /**
     * Creates new form SİPARİSUYGULAMA
     */
    public SİPARİSUYGULAMA() {
        initComponents();
    }
    public void siparisleriGoster(){
        String message=" ";
        int tutar=0;
        if (siparisler.isEmpty()) {
            
            message = "Siparişiniz Bulunmamaktadır";
            
        }
        else {
            message += "Siparişler\n";
            
            
            for (Map.Entry<String,Integer> entry : siparisler.entrySet()) {
                
                message += entry.getKey() + "\n";
                tutar += entry.getValue();
                
            }
            message += "Toplam Tutar : " + tutar;
            
        }
        
        JOptionPane.showMessageDialog(this, message);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iskender = new javax.swing.JCheckBox();
        kebap = new javax.swing.JCheckBox();
        ayran = new javax.swing.JCheckBox();
        siparis_goster = new javax.swing.JToggleButton();
        salata = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menü");

        iskender.setText("İskender-15 TL");
        iskender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iskenderActionPerformed(evt);
            }
        });

        kebap.setText("Kebap-20 TL");
        kebap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kebapActionPerformed(evt);
            }
        });

        ayran.setText("Ayran-2 TL");
        ayran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ayranActionPerformed(evt);
            }
        });

        siparis_goster.setText("Siparişleri Göster");
        siparis_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siparis_gosterActionPerformed(evt);
            }
        });

        salata.setText("Salata-5 TL");
        salata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(iskender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(kebap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ayran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(salata))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(siparis_goster)))
                .addGap(62, 62, 62))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(iskender, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kebap)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ayran)
                    .addComponent(salata))
                .addGap(18, 18, 18)
                .addComponent(siparis_goster)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iskenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iskenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_iskenderActionPerformed

    private void siparis_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siparis_gosterActionPerformed
        if(iskender.isSelected()){
            siparisler.put("İskender", 15);
            
        }
        else {
            siparisler.remove("İskender");
            
        }
        if (kebap.isSelected()) {
            
            siparisler.put("Kebap",20);
            
        }
        else {
            siparisler.remove("Kebap");
            
        }
        if (salata.isSelected()) {
            
            siparisler.put("Salata",5);
            
        }
        else {
            siparisler.remove("Salata");
            
        }
        if (ayran.isSelected()) {
            
            siparisler.put("Ayran",2);
            
        }
        else {
            siparisler.remove("Ayran");
            
        }
        siparisleriGoster();
    }//GEN-LAST:event_siparis_gosterActionPerformed

    private void kebapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kebapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kebapActionPerformed

    private void ayranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ayranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ayranActionPerformed

    private void salataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SİPARİSUYGULAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SİPARİSUYGULAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SİPARİSUYGULAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SİPARİSUYGULAMA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SİPARİSUYGULAMA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayran;
    private javax.swing.JCheckBox iskender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox kebap;
    private javax.swing.JCheckBox salata;
    private javax.swing.JToggleButton siparis_goster;
    // End of variables declaration//GEN-END:variables
}
