/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import gui.ayarlar.ActionAyarlari;
import gui.ayarlar.ButtonAyarlari;
import gui.ayarlar.IDuzenleyici;
import gui.ayarlar.IconAyarları;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;

/**
 *
 * @author feda1
 */
public class HesapEkrani extends javax.swing.JFrame implements IDuzenleyici{

    /**
     * Creates new form HesapEkrani
     */
    public HesapEkrani() {
        initComponents();
        getEdits();
    } 

    @Override
    public void getEdits() {
this.setLocationRelativeTo(null);
HesapEkranıPanel.setFocusable(true);
    }
    
    private void setBgFg(Component c){
        ButtonAyarlari.setBgFg((JButton)c, Color.BLACK, Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HesapEkranıPanel = new javax.swing.JPanel();
        hosgeldinLabel = new javax.swing.JLabel();
        kullanıcıAdıLabel = new javax.swing.JLabel();
        IconLabel = new javax.swing.JLabel();
        bakiyeLabel = new javax.swing.JLabel();
        paraCekIconLabel = new javax.swing.JLabel();
        paraCekButton = new javax.swing.JButton();
        paraYatırIconLabel = new javax.swing.JLabel();
        paraYatırButton = new javax.swing.JButton();
        HavaleIconLabel = new javax.swing.JLabel();
        havaleButton = new javax.swing.JButton();
        odemeIconLabel = new javax.swing.JLabel();
        odemeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sweet Bank Hesap  Ekranı");

        HesapEkranıPanel.setBackground(new java.awt.Color(153, 153, 153));

        hosgeldinLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        hosgeldinLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hosgeldinLabel.setText("HOŞGELDİN");

        kullanıcıAdıLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        kullanıcıAdıLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kullanıcıAdıLabel.setText("[Kullanıcı Adı Soyadı]");

        IconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/turkishLiraIcon.png"))); // NOI18N

        bakiyeLabel.setFont(new java.awt.Font("Verdana", 1, 32)); // NOI18N
        bakiyeLabel.setText("[Bakiye]");

        paraCekIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paraCekIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/withdrawMoneyIcon.png"))); // NOI18N
        paraCekIconLabel.setToolTipText("");

        paraCekButton.setBackground(new java.awt.Color(0, 51, 51));
        paraCekButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        paraCekButton.setForeground(new java.awt.Color(153, 153, 153));
        paraCekButton.setText("Para Çek");
        paraCekButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paraCekButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paraCekButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paraCekButtonMouseEntered(evt);
            }
        });
        paraCekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraCekButtonActionPerformed(evt);
            }
        });

        paraYatırIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        paraYatırIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/depositeIcon1.png"))); // NOI18N
        paraYatırIconLabel.setToolTipText("");

        paraYatırButton.setBackground(new java.awt.Color(0, 51, 51));
        paraYatırButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        paraYatırButton.setForeground(new java.awt.Color(153, 153, 153));
        paraYatırButton.setText("Para Yatır");
        paraYatırButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        paraYatırButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paraYatırButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paraYatırButtonMouseEntered(evt);
            }
        });
        paraYatırButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraYatırButtonActionPerformed(evt);
            }
        });

        HavaleIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HavaleIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/transferIcon1.png"))); // NOI18N
        HavaleIconLabel.setToolTipText("");

        havaleButton.setBackground(new java.awt.Color(102, 102, 0));
        havaleButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        havaleButton.setForeground(new java.awt.Color(153, 153, 153));
        havaleButton.setText("Havale");
        havaleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        havaleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                havaleButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                havaleButtonMouseEntered(evt);
            }
        });
        havaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                havaleButtonActionPerformed(evt);
            }
        });

        odemeIconLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        odemeIconLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/paymentIcon1.png"))); // NOI18N
        odemeIconLabel.setToolTipText("");

        odemeButton.setBackground(new java.awt.Color(0, 153, 204));
        odemeButton.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        odemeButton.setForeground(new java.awt.Color(102, 102, 102));
        odemeButton.setText("Ödemeler");
        odemeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        odemeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                odemeButtonMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                odemeButtonMouseEntered(evt);
            }
        });
        odemeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odemeButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/logoutIcon.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/Iconlar/settingIcon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout HesapEkranıPanelLayout = new javax.swing.GroupLayout(HesapEkranıPanel);
        HesapEkranıPanel.setLayout(HesapEkranıPanelLayout);
        HesapEkranıPanelLayout.setHorizontalGroup(
            HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                .addGroup(HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(kullanıcıAdıLabel))
                    .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(paraCekIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paraCekButton))
                        .addGap(39, 39, 39)
                        .addGroup(HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(paraYatırIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paraYatırButton))
                        .addGap(33, 33, 33)
                        .addGroup(HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(HavaleIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(havaleButton))
                        .addGap(35, 35, 35)
                        .addGroup(HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(odemeIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(odemeButton))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(bakiyeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(218, 218, 218)
                .addComponent(hosgeldinLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(27, 27, 27))
        );
        HesapEkranıPanelLayout.setVerticalGroup(
            HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                .addGroup(HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(hosgeldinLabel))
                    .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addGap(32, 32, 32)
                .addComponent(kullanıcıAdıLabel)
                .addGap(34, 34, 34)
                .addGroup(HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bakiyeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HesapEkranıPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                        .addComponent(paraCekIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paraCekButton))
                    .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                        .addComponent(paraYatırIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(paraYatırButton))
                    .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                        .addComponent(HavaleIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(havaleButton))
                    .addGroup(HesapEkranıPanelLayout.createSequentialGroup()
                        .addComponent(odemeIconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(odemeButton)))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HesapEkranıPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HesapEkranıPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paraYatırButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraYatırButtonActionPerformed
        ActionAyarlari.setVisible(this, new ParaYatırmaEkrani());
    }//GEN-LAST:event_paraYatırButtonActionPerformed

    private void paraCekButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraCekButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconAyarları.changeIcon(paraCekIconLabel,"withdrawMoneyIcon");
    }//GEN-LAST:event_paraCekButtonMouseEntered

    private void paraCekButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraCekButtonMouseExited
        ButtonAyarlari.setOriginalBg((JButton)evt.getComponent());
        IconAyarları.setOriginalIcon(paraCekIconLabel);
    }//GEN-LAST:event_paraCekButtonMouseExited

    private void paraYatırButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraYatırButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconAyarları.changeIcon(paraYatırIconLabel,"depositeIcon2");
    }//GEN-LAST:event_paraYatırButtonMouseEntered

    private void paraYatırButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paraYatırButtonMouseExited
        ButtonAyarlari.setOriginalBg((JButton)evt.getComponent());
        IconAyarları.setOriginalIcon(paraYatırIconLabel);
    }//GEN-LAST:event_paraYatırButtonMouseExited

    private void havaleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_havaleButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconAyarları.changeIcon(HavaleIconLabel,"transferIcon2");
    }//GEN-LAST:event_havaleButtonMouseEntered

    private void havaleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_havaleButtonMouseExited
        ButtonAyarlari.setOriginalBg((JButton)evt.getComponent());
        IconAyarları.setOriginalIcon(HavaleIconLabel);
    }//GEN-LAST:event_havaleButtonMouseExited

    private void odemeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odemeButtonMouseEntered
        this.setBgFg(evt.getComponent());
        IconAyarları.changeIcon(odemeIconLabel,"paymentIcon2");
    }//GEN-LAST:event_odemeButtonMouseEntered

    private void odemeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_odemeButtonMouseExited
        ButtonAyarlari.setOriginalBg((JButton)evt.getComponent());
        IconAyarları.setOriginalIcon(odemeIconLabel);
    }//GEN-LAST:event_odemeButtonMouseExited

    private void paraCekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraCekButtonActionPerformed
       ActionAyarlari.setVisible(this, new ParaCekmeEkrani());
    }//GEN-LAST:event_paraCekButtonActionPerformed

    private void havaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_havaleButtonActionPerformed
       ActionAyarlari.setVisible(this, new HavaleEkrani());
    }//GEN-LAST:event_havaleButtonActionPerformed

    private void odemeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemeButtonActionPerformed
       ActionAyarlari.setVisible(this, new ÖdemelerEkrani());
    }//GEN-LAST:event_odemeButtonActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       ActionAyarlari.setVisible(this, new AyarlarEkrani());
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        ActionAyarlari.setVisible(this, new GirisEkrani());
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HesapEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HavaleIconLabel;
    private javax.swing.JPanel HesapEkranıPanel;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JLabel bakiyeLabel;
    private javax.swing.JButton havaleButton;
    private javax.swing.JLabel hosgeldinLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel kullanıcıAdıLabel;
    private javax.swing.JButton odemeButton;
    private javax.swing.JLabel odemeIconLabel;
    private javax.swing.JButton paraCekButton;
    private javax.swing.JLabel paraCekIconLabel;
    private javax.swing.JButton paraYatırButton;
    private javax.swing.JLabel paraYatırIconLabel;
    // End of variables declaration//GEN-END:variables
}
